/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package codecs.api;

import codecs.ber.types.BerEnum;

import java.math.BigInteger;


public class AdmEstCause extends BerEnum {

	private static final long serialVersionUID = 1L;

	public AdmEstCause() {
	}

	public AdmEstCause(byte[] code) {
		super(code);
	}

	public AdmEstCause(BigInteger value) {
		super(value);
	}

	public AdmEstCause(long value) {
		super(value);
	}

}
