/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package codecs.api;

import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;

import java.math.BigInteger;


public class ENBUES1APID extends BerInteger {

	private static final long serialVersionUID = 1L;

	public ENBUES1APID() {
	}

	public ENBUES1APID(byte[] code) {
		super(code);
	}

	public ENBUES1APID(BigInteger value) {
		super(value);
	}

	public ENBUES1APID(long value) {
		super(value);
	}

}
