/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package codecs.api;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import codecs.ber.*;
import codecs.ber.types.*;
import codecs.ber.types.string.*;


public class ENBUES1APID extends BerInteger {

	private static final long serialVersionUID = 1L;

	public ENBUES1APID() {
	}

	public ENBUES1APID(byte[] code) {
		super(code);
	}

	public ENBUES1APID(BigInteger value) {
		super(value);
	}

	public ENBUES1APID(long value) {
		super(value);
	}

}
