/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package codecs.api;

import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;

import java.math.BigInteger;


public class ERABID extends BerInteger {

	private static final long serialVersionUID = 1L;

	public ERABID() {
	}

	public ERABID(byte[] code) {
		super(code);
	}

	public ERABID(BigInteger value) {
		super(value);
	}

	public ERABID(long value) {
		super(value);
	}

	@Override
	public int hashCode() {
		return value.intValue();
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof ERABID) {
			return value.intValue() == ((ERABID) obj).intValue();
		}
		return super.equals(obj);
	}
}
