/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package codecs.api;

import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;

import java.math.BigInteger;


public class ERABDecision extends BerEnum {

	private static final long serialVersionUID = 1L;

	public ERABDecision() {
	}

	public ERABDecision(byte[] code) {
		super(code);
	}

	public ERABDecision(BigInteger value) {
		super(value);
	}

	public ERABDecision(long value) {
		super(value);
	}

}
