/**
 * This class file was automatically generated by jASN1 v1.8.2 (http://www.openmuc.org)
 */

package codecs.api;

import codecs.ber.types.BerInteger;

import java.math.BigInteger;


public class Hysteresis extends BerInteger {

    private static final long serialVersionUID = 1L;

    public Hysteresis() {
    }

    public Hysteresis(byte[] code) {
        super(code);
    }

    public Hysteresis(BigInteger value) {
        super(value);
    }

    public Hysteresis(long value) {
        super(value);
    }

}
