/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package codecs.api;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import java.util.Objects;

import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class MMEUES1APID extends BerInteger {

	private static final long serialVersionUID = 1L;

	public MMEUES1APID() {
	}

	public MMEUES1APID(byte[] code) {
		super(code);
	}

	public MMEUES1APID(BigInteger value) {
		super(value);
	}

	public MMEUES1APID(long value) {
		super(value);
	}

	@Override
	public int hashCode() {
		return value.hashCode();
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof MMEUES1APID) {
			return Objects.equals(value, ((MMEUES1APID) obj).value);
		}
		return super.equals(obj);
	}
}
