/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package codecs.api;

import org.openmuc.jasn1.ber.types.BerOctetString;


public class PLMNIdentity extends BerOctetString {

	private static final long serialVersionUID = 1L;

	public PLMNIdentity() {
	}

	public PLMNIdentity(byte[] value) {
		super(value);
	}

}
