/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package codecs.api;

import org.openmuc.jasn1.ber.types.BerInteger;

import java.math.BigInteger;


public class QCI extends BerInteger {

	private static final long serialVersionUID = 1L;

	public QCI() {
	}

	public QCI(byte[] code) {
		super(code);
	}

	public QCI(BigInteger value) {
		super(value);
	}

	public QCI(long value) {
		super(value);
	}

}
