/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package codecs.api;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class RXSigRepQty extends BerEnum {

	private static final long serialVersionUID = 1L;

	public RXSigRepQty() {
	}

	public RXSigRepQty(byte[] code) {
		super(code);
	}

	public RXSigRepQty(BigInteger value) {
		super(value);
	}

	public RXSigRepQty(long value) {
		super(value);
	}

}
