/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package codecs.api;

import org.openmuc.jasn1.ber.types.BerEnum;

import java.math.BigInteger;


public class XICICPA extends BerEnum {

	private static final long serialVersionUID = 1L;

	public XICICPA() {
	}

	public XICICPA(byte[] code) {
		super(code);
	}

	public XICICPA(BigInteger value) {
		super(value);
	}

	public XICICPA(long value) {
		super(value);
	}

}
